### ISSUE TITLE
Store fonts locally

### ISSUE THREAD

**Issue by Stiofan** [AyeCode/wp-font-awesome-settings#5]
https://wptavern.com/german-court-fines-website-owner-for-violating-the-gdpr-by-using-google-hosted-fonts
https://wordpress.org/support/topic/plugin-is-not-gdpr-compliant/

We need to store FA locally.  There are some classes out there that do this and we will need this for fonts in BlockStrap theme soon also.

Lets discuss this before you start.

**Comment by kprajapatii** [comment]
Fixed
